services:
  otel_collector:
    image: docker.io/otel/opentelemetry-collector:0.120.0
    command:
      - --config=/etc/otel-config.yaml
    volumes:
      - ./pain/otel.yaml:/etc/otel-config.yaml
    # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/2039671f7b2781abb4de7f652431992b7f3de6f0/examples/demo/docker-compose.yaml#L29
    ports:
      - ${OTEL_PORT_GRPC:-4317}:4317   # OTLP gRPC receiver
      - ${OTEL_PORT_HTTP:-4318}:4318   # OTLP HTTP receiver
    expose:
      - 4317
      - 4318
    depends_on:
      - tempo
      - loki
      - prometheus

  loki:
    image: docker.io/grafana/loki:3.4.2
    command:
      - -config.file=/etc/loki-config.yaml
    volumes:
      - ./pain/loki.yaml:/etc/loki-config.yaml
    ports:
      - ${LOKI_LISTEN_HTTP_PORT:-3100}:3100
      - ${LOKI_ADVERTISE_PORT:-7946}:7946
      - ${LOKI_LISTEN_GRPC_PORT:-9095}:9095
    expose:
      - 3100
      - 7946
      - 9095

  prometheus:
    image: docker.io/prom/prometheus:v3.2.0
    command:
      - --web.enable-otlp-receiver
      - --storage.tsdb.retention.time=1h
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/config.yaml
    volumes:
      - ./pain/prometheus.yaml:/etc/prometheus/config.yaml
    ports:
      - ${PROMETHEUS_HTTP_PORT:-9090}:9090
    expose:
      - 9090

  tempo:
    image: docker.io/grafana/tempo:2.7.1
    command:
      - -config.file=/etc/tempo.yml
    volumes:
      - ./pain/tempo.yml:/etc/tempo.yml
    expose:
      - 4317
      - 3200
    ports:
      - ${TEMPO_HTTP_PORT:-3200}:3200

  grafana:
    image: docker.io/grafana/grafana:11.0.0
    volumes:
      - ./pain/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_FEATURE_TOGGLES_ENABLE: traceqlEditor
    ports:
      - ${GRAFANA_HTTP_PORT:-3000}:3000
    depends_on:
      - otel_collector

