[package]
name = "trayray"
version = "0.1.0"
edition = "2024"

[lib]
name = "trayray"
path = "./src/lib.rs"

[dependencies]
log = "0.4.33"
opentelemetry = "0.32.0"
opentelemetry-appender-log = "0.32.0"
opentelemetry-appender-tracing = "0.32.0"
opentelemetry-otlp = "0.32.0"
opentelemetry_sdk = "0.32.1"
tokio = {
    version = "1.53.1",
    features = ["macros", "rt-multi-thread"],
}
tracing = "0.1.44"
tracing-opentelemetry = "0.33.0"
tracing-subscriber = {
    version = "0.3.23",
    default-features = false,
    features = ["fmt", "env-filter", "registry", "ansi"],
}
