[package]
name = "http-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[dependencies]
duckdb = { version = "1.1.1", features = ["bundled", "json"] }
rocket = "0.5"
tracing = "0.1"
tracing-subscriber = "0.3"
