services:
  schemaregistry:
    image: confluentinc/cp-schema-registry:latest
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: 0.0.0.0:8081
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: WARN
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: nc -z localhost 8081 || exit 1
      interval: 3s
      retries: 10
    expose:
      - 8081
    ports:
      - ${SCHEMAREGISTRY_HTTP_PORT:-8081}:8081

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schemaregistry:8081
      LOGGING_LEVEL_COM_PROVECTUS: WARN
      LOGGING_LEVEL_ROOT: WARN
    depends_on:
      kafka:
        condition: service_healthy
      schemaregistry:
        condition: service_healthy
    ports:
      - ${KAFKA_UI_HTTP_PORT:-9093}:8080
