[package]
name = "crust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
smol = { version = "1.3.0", optional = true }

[features]
failures = []
future = ["dep:smol"]
