services:
  pg:
    image: docker.io/postgres:17.4
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
    volumes:
      - ./pg.conf:/var/lib/postgresql/data/postgresql.conf
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U $DB_USER -d $DB_NAME || exit 1
      interval: 3s
      retries: 10
