[package]
name = "pq-wal-receiver"
version = "0.1.0"
edition = "2024"

[lib]
name = "pq_wal_receiver"
path = "./src/lib.rs"

[[bin]]
name = "recv"
path = "./src/bin/recv.rs"

[dependencies]
time = { version = "0.3.41", features = ["macros"] }

[build-dependencies]
bindgen = "0.71.0"
