services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.6-alpine
    environment:
      CLICKHOUSE_DB: logs
      CLICKHOUSE_USER: log
      CLICKHOUSE_PASSWORD: log
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    expose:
      - 8123
      - 9000
      - 9011
    ports:
      - ${CLICKHOUSE_PORT:-18123}:8123
  grafana:
    image: docker.io/grafana/grafana:12.1.0
    ports:
      - ${GRAFANA_HTTP_PORT:-3000}:3000
    volumes:
      - ./clickhouse.yaml:/etc/grafana/provisioning/datasources/clickhouse.yaml
      - ./grafana.ini:/etc/grafana/grafana.ini
      - grafana-db:/var/lib/grafana

volumes:
  grafana-db:
