/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: scip.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "scip.pb-c.h"
void   scip__index__init
                     (Scip__Index         *message)
{
  static const Scip__Index init_value = SCIP__INDEX__INIT;
  *message = init_value;
}
size_t scip__index__get_packed_size
                     (const Scip__Index *message)
{
  assert(message->base.descriptor == &scip__index__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scip__index__pack
                     (const Scip__Index *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scip__index__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scip__index__pack_to_buffer
                     (const Scip__Index *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scip__index__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Scip__Index *
       scip__index__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Scip__Index *)
     protobuf_c_message_unpack (&scip__index__descriptor,
                                allocator, len, data);
}
void   scip__index__free_unpacked
                     (Scip__Index *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &scip__index__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scip__metadata__init
                     (Scip__Metadata         *message)
{
  static const Scip__Metadata init_value = SCIP__METADATA__INIT;
  *message = init_value;
}
size_t scip__metadata__get_packed_size
                     (const Scip__Metadata *message)
{
  assert(message->base.descriptor == &scip__metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scip__metadata__pack
                     (const Scip__Metadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scip__metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scip__metadata__pack_to_buffer
                     (const Scip__Metadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scip__metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Scip__Metadata *
       scip__metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Scip__Metadata *)
     protobuf_c_message_unpack (&scip__metadata__descriptor,
                                allocator, len, data);
}
void   scip__metadata__free_unpacked
                     (Scip__Metadata *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &scip__metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scip__tool_info__init
                     (Scip__ToolInfo         *message)
{
  static const Scip__ToolInfo init_value = SCIP__TOOL_INFO__INIT;
  *message = init_value;
}
size_t scip__tool_info__get_packed_size
                     (const Scip__ToolInfo *message)
{
  assert(message->base.descriptor == &scip__tool_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scip__tool_info__pack
                     (const Scip__ToolInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scip__tool_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scip__tool_info__pack_to_buffer
                     (const Scip__ToolInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scip__tool_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Scip__ToolInfo *
       scip__tool_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Scip__ToolInfo *)
     protobuf_c_message_unpack (&scip__tool_info__descriptor,
                                allocator, len, data);
}
void   scip__tool_info__free_unpacked
                     (Scip__ToolInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &scip__tool_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scip__document__init
                     (Scip__Document         *message)
{
  static const Scip__Document init_value = SCIP__DOCUMENT__INIT;
  *message = init_value;
}
size_t scip__document__get_packed_size
                     (const Scip__Document *message)
{
  assert(message->base.descriptor == &scip__document__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scip__document__pack
                     (const Scip__Document *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scip__document__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scip__document__pack_to_buffer
                     (const Scip__Document *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scip__document__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Scip__Document *
       scip__document__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Scip__Document *)
     protobuf_c_message_unpack (&scip__document__descriptor,
                                allocator, len, data);
}
void   scip__document__free_unpacked
                     (Scip__Document *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &scip__document__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scip__symbol__init
                     (Scip__Symbol         *message)
{
  static const Scip__Symbol init_value = SCIP__SYMBOL__INIT;
  *message = init_value;
}
size_t scip__symbol__get_packed_size
                     (const Scip__Symbol *message)
{
  assert(message->base.descriptor == &scip__symbol__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scip__symbol__pack
                     (const Scip__Symbol *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scip__symbol__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scip__symbol__pack_to_buffer
                     (const Scip__Symbol *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scip__symbol__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Scip__Symbol *
       scip__symbol__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Scip__Symbol *)
     protobuf_c_message_unpack (&scip__symbol__descriptor,
                                allocator, len, data);
}
void   scip__symbol__free_unpacked
                     (Scip__Symbol *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &scip__symbol__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scip__package__init
                     (Scip__Package         *message)
{
  static const Scip__Package init_value = SCIP__PACKAGE__INIT;
  *message = init_value;
}
size_t scip__package__get_packed_size
                     (const Scip__Package *message)
{
  assert(message->base.descriptor == &scip__package__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scip__package__pack
                     (const Scip__Package *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scip__package__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scip__package__pack_to_buffer
                     (const Scip__Package *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scip__package__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Scip__Package *
       scip__package__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Scip__Package *)
     protobuf_c_message_unpack (&scip__package__descriptor,
                                allocator, len, data);
}
void   scip__package__free_unpacked
                     (Scip__Package *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &scip__package__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scip__descriptor__init
                     (Scip__Descriptor         *message)
{
  static const Scip__Descriptor init_value = SCIP__DESCRIPTOR__INIT;
  *message = init_value;
}
size_t scip__descriptor__get_packed_size
                     (const Scip__Descriptor *message)
{
  assert(message->base.descriptor == &scip__descriptor__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scip__descriptor__pack
                     (const Scip__Descriptor *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scip__descriptor__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scip__descriptor__pack_to_buffer
                     (const Scip__Descriptor *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scip__descriptor__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Scip__Descriptor *
       scip__descriptor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Scip__Descriptor *)
     protobuf_c_message_unpack (&scip__descriptor__descriptor,
                                allocator, len, data);
}
void   scip__descriptor__free_unpacked
                     (Scip__Descriptor *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &scip__descriptor__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scip__symbol_information__init
                     (Scip__SymbolInformation         *message)
{
  static const Scip__SymbolInformation init_value = SCIP__SYMBOL_INFORMATION__INIT;
  *message = init_value;
}
size_t scip__symbol_information__get_packed_size
                     (const Scip__SymbolInformation *message)
{
  assert(message->base.descriptor == &scip__symbol_information__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scip__symbol_information__pack
                     (const Scip__SymbolInformation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scip__symbol_information__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scip__symbol_information__pack_to_buffer
                     (const Scip__SymbolInformation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scip__symbol_information__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Scip__SymbolInformation *
       scip__symbol_information__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Scip__SymbolInformation *)
     protobuf_c_message_unpack (&scip__symbol_information__descriptor,
                                allocator, len, data);
}
void   scip__symbol_information__free_unpacked
                     (Scip__SymbolInformation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &scip__symbol_information__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scip__relationship__init
                     (Scip__Relationship         *message)
{
  static const Scip__Relationship init_value = SCIP__RELATIONSHIP__INIT;
  *message = init_value;
}
size_t scip__relationship__get_packed_size
                     (const Scip__Relationship *message)
{
  assert(message->base.descriptor == &scip__relationship__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scip__relationship__pack
                     (const Scip__Relationship *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scip__relationship__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scip__relationship__pack_to_buffer
                     (const Scip__Relationship *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scip__relationship__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Scip__Relationship *
       scip__relationship__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Scip__Relationship *)
     protobuf_c_message_unpack (&scip__relationship__descriptor,
                                allocator, len, data);
}
void   scip__relationship__free_unpacked
                     (Scip__Relationship *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &scip__relationship__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scip__occurrence__init
                     (Scip__Occurrence         *message)
{
  static const Scip__Occurrence init_value = SCIP__OCCURRENCE__INIT;
  *message = init_value;
}
size_t scip__occurrence__get_packed_size
                     (const Scip__Occurrence *message)
{
  assert(message->base.descriptor == &scip__occurrence__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scip__occurrence__pack
                     (const Scip__Occurrence *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scip__occurrence__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scip__occurrence__pack_to_buffer
                     (const Scip__Occurrence *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scip__occurrence__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Scip__Occurrence *
       scip__occurrence__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Scip__Occurrence *)
     protobuf_c_message_unpack (&scip__occurrence__descriptor,
                                allocator, len, data);
}
void   scip__occurrence__free_unpacked
                     (Scip__Occurrence *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &scip__occurrence__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scip__diagnostic__init
                     (Scip__Diagnostic         *message)
{
  static const Scip__Diagnostic init_value = SCIP__DIAGNOSTIC__INIT;
  *message = init_value;
}
size_t scip__diagnostic__get_packed_size
                     (const Scip__Diagnostic *message)
{
  assert(message->base.descriptor == &scip__diagnostic__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scip__diagnostic__pack
                     (const Scip__Diagnostic *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scip__diagnostic__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scip__diagnostic__pack_to_buffer
                     (const Scip__Diagnostic *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scip__diagnostic__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Scip__Diagnostic *
       scip__diagnostic__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Scip__Diagnostic *)
     protobuf_c_message_unpack (&scip__diagnostic__descriptor,
                                allocator, len, data);
}
void   scip__diagnostic__free_unpacked
                     (Scip__Diagnostic *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &scip__diagnostic__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor scip__index__field_descriptors[3] =
{
  {
    "metadata",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Scip__Index, metadata),
    &scip__metadata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "documents",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Scip__Index, n_documents),
    offsetof(Scip__Index, documents),
    &scip__document__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "external_symbols",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Scip__Index, n_external_symbols),
    offsetof(Scip__Index, external_symbols),
    &scip__symbol_information__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scip__index__field_indices_by_name[] = {
  1,   /* field[1] = documents */
  2,   /* field[2] = external_symbols */
  0,   /* field[0] = metadata */
};
static const ProtobufCIntRange scip__index__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor scip__index__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "scip.Index",
  "Index",
  "Scip__Index",
  "scip",
  sizeof(Scip__Index),
  3,
  scip__index__field_descriptors,
  scip__index__field_indices_by_name,
  1,  scip__index__number_ranges,
  (ProtobufCMessageInit) scip__index__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scip__metadata__field_descriptors[4] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Scip__Metadata, version),
    &scip__protocol_version__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tool_info",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Scip__Metadata, tool_info),
    &scip__tool_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "project_root",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Scip__Metadata, project_root),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "text_document_encoding",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Scip__Metadata, text_document_encoding),
    &scip__text_encoding__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scip__metadata__field_indices_by_name[] = {
  2,   /* field[2] = project_root */
  3,   /* field[3] = text_document_encoding */
  1,   /* field[1] = tool_info */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange scip__metadata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor scip__metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "scip.Metadata",
  "Metadata",
  "Scip__Metadata",
  "scip",
  sizeof(Scip__Metadata),
  4,
  scip__metadata__field_descriptors,
  scip__metadata__field_indices_by_name,
  1,  scip__metadata__number_ranges,
  (ProtobufCMessageInit) scip__metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scip__tool_info__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Scip__ToolInfo, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Scip__ToolInfo, version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "arguments",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Scip__ToolInfo, n_arguments),
    offsetof(Scip__ToolInfo, arguments),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scip__tool_info__field_indices_by_name[] = {
  2,   /* field[2] = arguments */
  0,   /* field[0] = name */
  1,   /* field[1] = version */
};
static const ProtobufCIntRange scip__tool_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor scip__tool_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "scip.ToolInfo",
  "ToolInfo",
  "Scip__ToolInfo",
  "scip",
  sizeof(Scip__ToolInfo),
  3,
  scip__tool_info__field_descriptors,
  scip__tool_info__field_indices_by_name,
  1,  scip__tool_info__number_ranges,
  (ProtobufCMessageInit) scip__tool_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scip__document__field_descriptors[6] =
{
  {
    "relative_path",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Scip__Document, relative_path),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "occurrences",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Scip__Document, n_occurrences),
    offsetof(Scip__Document, occurrences),
    &scip__occurrence__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "symbols",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Scip__Document, n_symbols),
    offsetof(Scip__Document, symbols),
    &scip__symbol_information__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "language",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Scip__Document, language),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "text",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Scip__Document, text),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position_encoding",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Scip__Document, position_encoding),
    &scip__position_encoding__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scip__document__field_indices_by_name[] = {
  3,   /* field[3] = language */
  1,   /* field[1] = occurrences */
  5,   /* field[5] = position_encoding */
  0,   /* field[0] = relative_path */
  2,   /* field[2] = symbols */
  4,   /* field[4] = text */
};
static const ProtobufCIntRange scip__document__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor scip__document__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "scip.Document",
  "Document",
  "Scip__Document",
  "scip",
  sizeof(Scip__Document),
  6,
  scip__document__field_descriptors,
  scip__document__field_indices_by_name,
  1,  scip__document__number_ranges,
  (ProtobufCMessageInit) scip__document__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scip__symbol__field_descriptors[3] =
{
  {
    "scheme",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Scip__Symbol, scheme),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "package",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Scip__Symbol, package),
    &scip__package__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "descriptors",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Scip__Symbol, n_descriptors),
    offsetof(Scip__Symbol, descriptors),
    &scip__descriptor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scip__symbol__field_indices_by_name[] = {
  2,   /* field[2] = descriptors */
  1,   /* field[1] = package */
  0,   /* field[0] = scheme */
};
static const ProtobufCIntRange scip__symbol__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor scip__symbol__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "scip.Symbol",
  "Symbol",
  "Scip__Symbol",
  "scip",
  sizeof(Scip__Symbol),
  3,
  scip__symbol__field_descriptors,
  scip__symbol__field_indices_by_name,
  1,  scip__symbol__number_ranges,
  (ProtobufCMessageInit) scip__symbol__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scip__package__field_descriptors[3] =
{
  {
    "manager",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Scip__Package, manager),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Scip__Package, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Scip__Package, version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scip__package__field_indices_by_name[] = {
  0,   /* field[0] = manager */
  1,   /* field[1] = name */
  2,   /* field[2] = version */
};
static const ProtobufCIntRange scip__package__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor scip__package__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "scip.Package",
  "Package",
  "Scip__Package",
  "scip",
  sizeof(Scip__Package),
  3,
  scip__package__field_descriptors,
  scip__package__field_indices_by_name,
  1,  scip__package__number_ranges,
  (ProtobufCMessageInit) scip__package__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue scip__descriptor__suffix__enum_values_by_number[10] =
{
  { "UnspecifiedSuffix", "SCIP__DESCRIPTOR__SUFFIX__UnspecifiedSuffix", 0 },
  { "Namespace", "SCIP__DESCRIPTOR__SUFFIX__Namespace", 1 },
  { "Type", "SCIP__DESCRIPTOR__SUFFIX__Type", 2 },
  { "Term", "SCIP__DESCRIPTOR__SUFFIX__Term", 3 },
  { "Method", "SCIP__DESCRIPTOR__SUFFIX__Method", 4 },
  { "TypeParameter", "SCIP__DESCRIPTOR__SUFFIX__TypeParameter", 5 },
  { "Parameter", "SCIP__DESCRIPTOR__SUFFIX__Parameter", 6 },
  { "Meta", "SCIP__DESCRIPTOR__SUFFIX__Meta", 7 },
  { "Local", "SCIP__DESCRIPTOR__SUFFIX__Local", 8 },
  { "Macro", "SCIP__DESCRIPTOR__SUFFIX__Macro", 9 },
};
static const ProtobufCIntRange scip__descriptor__suffix__value_ranges[] = {
{0, 0},{0, 10}
};
static const ProtobufCEnumValueIndex scip__descriptor__suffix__enum_values_by_name[11] =
{
  { "Local", 8 },
  { "Macro", 9 },
  { "Meta", 7 },
  { "Method", 4 },
  { "Namespace", 1 },
  { "Package", 1 },
  { "Parameter", 6 },
  { "Term", 3 },
  { "Type", 2 },
  { "TypeParameter", 5 },
  { "UnspecifiedSuffix", 0 },
};
const ProtobufCEnumDescriptor scip__descriptor__suffix__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "scip.Descriptor.Suffix",
  "Suffix",
  "Scip__Descriptor__Suffix",
  "scip",
  10,
  scip__descriptor__suffix__enum_values_by_number,
  11,
  scip__descriptor__suffix__enum_values_by_name,
  1,
  scip__descriptor__suffix__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor scip__descriptor__field_descriptors[3] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Scip__Descriptor, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "disambiguator",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Scip__Descriptor, disambiguator),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "suffix",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Scip__Descriptor, suffix),
    &scip__descriptor__suffix__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scip__descriptor__field_indices_by_name[] = {
  1,   /* field[1] = disambiguator */
  0,   /* field[0] = name */
  2,   /* field[2] = suffix */
};
static const ProtobufCIntRange scip__descriptor__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor scip__descriptor__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "scip.Descriptor",
  "Descriptor",
  "Scip__Descriptor",
  "scip",
  sizeof(Scip__Descriptor),
  3,
  scip__descriptor__field_descriptors,
  scip__descriptor__field_indices_by_name,
  1,  scip__descriptor__number_ranges,
  (ProtobufCMessageInit) scip__descriptor__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue scip__symbol_information__kind__enum_values_by_number[86] =
{
  { "UnspecifiedKind", "SCIP__SYMBOL_INFORMATION__KIND__UnspecifiedKind", 0 },
  { "Array", "SCIP__SYMBOL_INFORMATION__KIND__Array", 1 },
  { "Assertion", "SCIP__SYMBOL_INFORMATION__KIND__Assertion", 2 },
  { "AssociatedType", "SCIP__SYMBOL_INFORMATION__KIND__AssociatedType", 3 },
  { "Attribute", "SCIP__SYMBOL_INFORMATION__KIND__Attribute", 4 },
  { "Axiom", "SCIP__SYMBOL_INFORMATION__KIND__Axiom", 5 },
  { "Boolean", "SCIP__SYMBOL_INFORMATION__KIND__Boolean", 6 },
  { "Class", "SCIP__SYMBOL_INFORMATION__KIND__Class", 7 },
  { "Constant", "SCIP__SYMBOL_INFORMATION__KIND__Constant", 8 },
  { "Constructor", "SCIP__SYMBOL_INFORMATION__KIND__Constructor", 9 },
  { "DataFamily", "SCIP__SYMBOL_INFORMATION__KIND__DataFamily", 10 },
  { "Enum", "SCIP__SYMBOL_INFORMATION__KIND__Enum", 11 },
  { "EnumMember", "SCIP__SYMBOL_INFORMATION__KIND__EnumMember", 12 },
  { "Event", "SCIP__SYMBOL_INFORMATION__KIND__Event", 13 },
  { "Fact", "SCIP__SYMBOL_INFORMATION__KIND__Fact", 14 },
  { "Field", "SCIP__SYMBOL_INFORMATION__KIND__Field", 15 },
  { "File", "SCIP__SYMBOL_INFORMATION__KIND__File", 16 },
  { "Function", "SCIP__SYMBOL_INFORMATION__KIND__Function", 17 },
  { "Getter", "SCIP__SYMBOL_INFORMATION__KIND__Getter", 18 },
  { "Grammar", "SCIP__SYMBOL_INFORMATION__KIND__Grammar", 19 },
  { "Instance", "SCIP__SYMBOL_INFORMATION__KIND__Instance", 20 },
  { "Interface", "SCIP__SYMBOL_INFORMATION__KIND__Interface", 21 },
  { "Key", "SCIP__SYMBOL_INFORMATION__KIND__Key", 22 },
  { "Lang", "SCIP__SYMBOL_INFORMATION__KIND__Lang", 23 },
  { "Lemma", "SCIP__SYMBOL_INFORMATION__KIND__Lemma", 24 },
  { "Macro", "SCIP__SYMBOL_INFORMATION__KIND__Macro", 25 },
  { "Method", "SCIP__SYMBOL_INFORMATION__KIND__Method", 26 },
  { "MethodReceiver", "SCIP__SYMBOL_INFORMATION__KIND__MethodReceiver", 27 },
  { "Message", "SCIP__SYMBOL_INFORMATION__KIND__Message", 28 },
  { "Module", "SCIP__SYMBOL_INFORMATION__KIND__Module", 29 },
  { "Namespace", "SCIP__SYMBOL_INFORMATION__KIND__Namespace", 30 },
  { "Null", "SCIP__SYMBOL_INFORMATION__KIND__Null", 31 },
  { "Number", "SCIP__SYMBOL_INFORMATION__KIND__Number", 32 },
  { "Object", "SCIP__SYMBOL_INFORMATION__KIND__Object", 33 },
  { "Operator", "SCIP__SYMBOL_INFORMATION__KIND__Operator", 34 },
  { "Package", "SCIP__SYMBOL_INFORMATION__KIND__Package", 35 },
  { "PackageObject", "SCIP__SYMBOL_INFORMATION__KIND__PackageObject", 36 },
  { "Parameter", "SCIP__SYMBOL_INFORMATION__KIND__Parameter", 37 },
  { "ParameterLabel", "SCIP__SYMBOL_INFORMATION__KIND__ParameterLabel", 38 },
  { "Pattern", "SCIP__SYMBOL_INFORMATION__KIND__Pattern", 39 },
  { "Predicate", "SCIP__SYMBOL_INFORMATION__KIND__Predicate", 40 },
  { "Property", "SCIP__SYMBOL_INFORMATION__KIND__Property", 41 },
  { "Protocol", "SCIP__SYMBOL_INFORMATION__KIND__Protocol", 42 },
  { "Quasiquoter", "SCIP__SYMBOL_INFORMATION__KIND__Quasiquoter", 43 },
  { "SelfParameter", "SCIP__SYMBOL_INFORMATION__KIND__SelfParameter", 44 },
  { "Setter", "SCIP__SYMBOL_INFORMATION__KIND__Setter", 45 },
  { "Signature", "SCIP__SYMBOL_INFORMATION__KIND__Signature", 46 },
  { "Subscript", "SCIP__SYMBOL_INFORMATION__KIND__Subscript", 47 },
  { "String", "SCIP__SYMBOL_INFORMATION__KIND__String", 48 },
  { "Struct", "SCIP__SYMBOL_INFORMATION__KIND__Struct", 49 },
  { "Tactic", "SCIP__SYMBOL_INFORMATION__KIND__Tactic", 50 },
  { "Theorem", "SCIP__SYMBOL_INFORMATION__KIND__Theorem", 51 },
  { "ThisParameter", "SCIP__SYMBOL_INFORMATION__KIND__ThisParameter", 52 },
  { "Trait", "SCIP__SYMBOL_INFORMATION__KIND__Trait", 53 },
  { "Type", "SCIP__SYMBOL_INFORMATION__KIND__Type", 54 },
  { "TypeAlias", "SCIP__SYMBOL_INFORMATION__KIND__TypeAlias", 55 },
  { "TypeClass", "SCIP__SYMBOL_INFORMATION__KIND__TypeClass", 56 },
  { "TypeFamily", "SCIP__SYMBOL_INFORMATION__KIND__TypeFamily", 57 },
  { "TypeParameter", "SCIP__SYMBOL_INFORMATION__KIND__TypeParameter", 58 },
  { "Union", "SCIP__SYMBOL_INFORMATION__KIND__Union", 59 },
  { "Value", "SCIP__SYMBOL_INFORMATION__KIND__Value", 60 },
  { "Variable", "SCIP__SYMBOL_INFORMATION__KIND__Variable", 61 },
  { "Contract", "SCIP__SYMBOL_INFORMATION__KIND__Contract", 62 },
  { "Error", "SCIP__SYMBOL_INFORMATION__KIND__Error", 63 },
  { "Library", "SCIP__SYMBOL_INFORMATION__KIND__Library", 64 },
  { "Modifier", "SCIP__SYMBOL_INFORMATION__KIND__Modifier", 65 },
  { "AbstractMethod", "SCIP__SYMBOL_INFORMATION__KIND__AbstractMethod", 66 },
  { "MethodSpecification", "SCIP__SYMBOL_INFORMATION__KIND__MethodSpecification", 67 },
  { "ProtocolMethod", "SCIP__SYMBOL_INFORMATION__KIND__ProtocolMethod", 68 },
  { "PureVirtualMethod", "SCIP__SYMBOL_INFORMATION__KIND__PureVirtualMethod", 69 },
  { "TraitMethod", "SCIP__SYMBOL_INFORMATION__KIND__TraitMethod", 70 },
  { "TypeClassMethod", "SCIP__SYMBOL_INFORMATION__KIND__TypeClassMethod", 71 },
  { "Accessor", "SCIP__SYMBOL_INFORMATION__KIND__Accessor", 72 },
  { "Delegate", "SCIP__SYMBOL_INFORMATION__KIND__Delegate", 73 },
  { "MethodAlias", "SCIP__SYMBOL_INFORMATION__KIND__MethodAlias", 74 },
  { "SingletonClass", "SCIP__SYMBOL_INFORMATION__KIND__SingletonClass", 75 },
  { "SingletonMethod", "SCIP__SYMBOL_INFORMATION__KIND__SingletonMethod", 76 },
  { "StaticDataMember", "SCIP__SYMBOL_INFORMATION__KIND__StaticDataMember", 77 },
  { "StaticEvent", "SCIP__SYMBOL_INFORMATION__KIND__StaticEvent", 78 },
  { "StaticField", "SCIP__SYMBOL_INFORMATION__KIND__StaticField", 79 },
  { "StaticMethod", "SCIP__SYMBOL_INFORMATION__KIND__StaticMethod", 80 },
  { "StaticProperty", "SCIP__SYMBOL_INFORMATION__KIND__StaticProperty", 81 },
  { "StaticVariable", "SCIP__SYMBOL_INFORMATION__KIND__StaticVariable", 82 },
  { "Extension", "SCIP__SYMBOL_INFORMATION__KIND__Extension", 84 },
  { "Mixin", "SCIP__SYMBOL_INFORMATION__KIND__Mixin", 85 },
  { "Concept", "SCIP__SYMBOL_INFORMATION__KIND__Concept", 86 },
};
static const ProtobufCIntRange scip__symbol_information__kind__value_ranges[] = {
{0, 0},{84, 83},{0, 86}
};
static const ProtobufCEnumValueIndex scip__symbol_information__kind__enum_values_by_name[86] =
{
  { "AbstractMethod", 66 },
  { "Accessor", 72 },
  { "Array", 1 },
  { "Assertion", 2 },
  { "AssociatedType", 3 },
  { "Attribute", 4 },
  { "Axiom", 5 },
  { "Boolean", 6 },
  { "Class", 7 },
  { "Concept", 85 },
  { "Constant", 8 },
  { "Constructor", 9 },
  { "Contract", 62 },
  { "DataFamily", 10 },
  { "Delegate", 73 },
  { "Enum", 11 },
  { "EnumMember", 12 },
  { "Error", 63 },
  { "Event", 13 },
  { "Extension", 83 },
  { "Fact", 14 },
  { "Field", 15 },
  { "File", 16 },
  { "Function", 17 },
  { "Getter", 18 },
  { "Grammar", 19 },
  { "Instance", 20 },
  { "Interface", 21 },
  { "Key", 22 },
  { "Lang", 23 },
  { "Lemma", 24 },
  { "Library", 64 },
  { "Macro", 25 },
  { "Message", 28 },
  { "Method", 26 },
  { "MethodAlias", 74 },
  { "MethodReceiver", 27 },
  { "MethodSpecification", 67 },
  { "Mixin", 84 },
  { "Modifier", 65 },
  { "Module", 29 },
  { "Namespace", 30 },
  { "Null", 31 },
  { "Number", 32 },
  { "Object", 33 },
  { "Operator", 34 },
  { "Package", 35 },
  { "PackageObject", 36 },
  { "Parameter", 37 },
  { "ParameterLabel", 38 },
  { "Pattern", 39 },
  { "Predicate", 40 },
  { "Property", 41 },
  { "Protocol", 42 },
  { "ProtocolMethod", 68 },
  { "PureVirtualMethod", 69 },
  { "Quasiquoter", 43 },
  { "SelfParameter", 44 },
  { "Setter", 45 },
  { "Signature", 46 },
  { "SingletonClass", 75 },
  { "SingletonMethod", 76 },
  { "StaticDataMember", 77 },
  { "StaticEvent", 78 },
  { "StaticField", 79 },
  { "StaticMethod", 80 },
  { "StaticProperty", 81 },
  { "StaticVariable", 82 },
  { "String", 48 },
  { "Struct", 49 },
  { "Subscript", 47 },
  { "Tactic", 50 },
  { "Theorem", 51 },
  { "ThisParameter", 52 },
  { "Trait", 53 },
  { "TraitMethod", 70 },
  { "Type", 54 },
  { "TypeAlias", 55 },
  { "TypeClass", 56 },
  { "TypeClassMethod", 71 },
  { "TypeFamily", 57 },
  { "TypeParameter", 58 },
  { "Union", 59 },
  { "UnspecifiedKind", 0 },
  { "Value", 60 },
  { "Variable", 61 },
};
const ProtobufCEnumDescriptor scip__symbol_information__kind__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "scip.SymbolInformation.Kind",
  "Kind",
  "Scip__SymbolInformation__Kind",
  "scip",
  86,
  scip__symbol_information__kind__enum_values_by_number,
  86,
  scip__symbol_information__kind__enum_values_by_name,
  2,
  scip__symbol_information__kind__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor scip__symbol_information__field_descriptors[7] =
{
  {
    "symbol",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Scip__SymbolInformation, symbol),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "documentation",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Scip__SymbolInformation, n_documentation),
    offsetof(Scip__SymbolInformation, documentation),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "relationships",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Scip__SymbolInformation, n_relationships),
    offsetof(Scip__SymbolInformation, relationships),
    &scip__relationship__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "kind",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Scip__SymbolInformation, kind),
    &scip__symbol_information__kind__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "display_name",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Scip__SymbolInformation, display_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature_documentation",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Scip__SymbolInformation, signature_documentation),
    &scip__document__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enclosing_symbol",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Scip__SymbolInformation, enclosing_symbol),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scip__symbol_information__field_indices_by_name[] = {
  4,   /* field[4] = display_name */
  1,   /* field[1] = documentation */
  6,   /* field[6] = enclosing_symbol */
  3,   /* field[3] = kind */
  2,   /* field[2] = relationships */
  5,   /* field[5] = signature_documentation */
  0,   /* field[0] = symbol */
};
static const ProtobufCIntRange scip__symbol_information__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor scip__symbol_information__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "scip.SymbolInformation",
  "SymbolInformation",
  "Scip__SymbolInformation",
  "scip",
  sizeof(Scip__SymbolInformation),
  7,
  scip__symbol_information__field_descriptors,
  scip__symbol_information__field_indices_by_name,
  2,  scip__symbol_information__number_ranges,
  (ProtobufCMessageInit) scip__symbol_information__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scip__relationship__field_descriptors[5] =
{
  {
    "symbol",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Scip__Relationship, symbol),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_reference",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Scip__Relationship, is_reference),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_implementation",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Scip__Relationship, is_implementation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_type_definition",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Scip__Relationship, is_type_definition),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_definition",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Scip__Relationship, is_definition),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scip__relationship__field_indices_by_name[] = {
  4,   /* field[4] = is_definition */
  2,   /* field[2] = is_implementation */
  1,   /* field[1] = is_reference */
  3,   /* field[3] = is_type_definition */
  0,   /* field[0] = symbol */
};
static const ProtobufCIntRange scip__relationship__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor scip__relationship__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "scip.Relationship",
  "Relationship",
  "Scip__Relationship",
  "scip",
  sizeof(Scip__Relationship),
  5,
  scip__relationship__field_descriptors,
  scip__relationship__field_indices_by_name,
  1,  scip__relationship__number_ranges,
  (ProtobufCMessageInit) scip__relationship__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scip__occurrence__field_descriptors[7] =
{
  {
    "range",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Scip__Occurrence, n_range),
    offsetof(Scip__Occurrence, range),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "symbol",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Scip__Occurrence, symbol),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "symbol_roles",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Scip__Occurrence, symbol_roles),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "override_documentation",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Scip__Occurrence, n_override_documentation),
    offsetof(Scip__Occurrence, override_documentation),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "syntax_kind",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Scip__Occurrence, syntax_kind),
    &scip__syntax_kind__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "diagnostics",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Scip__Occurrence, n_diagnostics),
    offsetof(Scip__Occurrence, diagnostics),
    &scip__diagnostic__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enclosing_range",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Scip__Occurrence, n_enclosing_range),
    offsetof(Scip__Occurrence, enclosing_range),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scip__occurrence__field_indices_by_name[] = {
  5,   /* field[5] = diagnostics */
  6,   /* field[6] = enclosing_range */
  3,   /* field[3] = override_documentation */
  0,   /* field[0] = range */
  1,   /* field[1] = symbol */
  2,   /* field[2] = symbol_roles */
  4,   /* field[4] = syntax_kind */
};
static const ProtobufCIntRange scip__occurrence__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor scip__occurrence__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "scip.Occurrence",
  "Occurrence",
  "Scip__Occurrence",
  "scip",
  sizeof(Scip__Occurrence),
  7,
  scip__occurrence__field_descriptors,
  scip__occurrence__field_indices_by_name,
  1,  scip__occurrence__number_ranges,
  (ProtobufCMessageInit) scip__occurrence__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scip__diagnostic__field_descriptors[5] =
{
  {
    "severity",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Scip__Diagnostic, severity),
    &scip__severity__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Scip__Diagnostic, code),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Scip__Diagnostic, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Scip__Diagnostic, source),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tags",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Scip__Diagnostic, n_tags),
    offsetof(Scip__Diagnostic, tags),
    &scip__diagnostic_tag__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scip__diagnostic__field_indices_by_name[] = {
  1,   /* field[1] = code */
  2,   /* field[2] = message */
  0,   /* field[0] = severity */
  3,   /* field[3] = source */
  4,   /* field[4] = tags */
};
static const ProtobufCIntRange scip__diagnostic__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor scip__diagnostic__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "scip.Diagnostic",
  "Diagnostic",
  "Scip__Diagnostic",
  "scip",
  sizeof(Scip__Diagnostic),
  5,
  scip__diagnostic__field_descriptors,
  scip__diagnostic__field_indices_by_name,
  1,  scip__diagnostic__number_ranges,
  (ProtobufCMessageInit) scip__diagnostic__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue scip__protocol_version__enum_values_by_number[1] =
{
  { "UnspecifiedProtocolVersion", "SCIP__PROTOCOL_VERSION__UnspecifiedProtocolVersion", 0 },
};
static const ProtobufCIntRange scip__protocol_version__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex scip__protocol_version__enum_values_by_name[1] =
{
  { "UnspecifiedProtocolVersion", 0 },
};
const ProtobufCEnumDescriptor scip__protocol_version__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "scip.ProtocolVersion",
  "ProtocolVersion",
  "Scip__ProtocolVersion",
  "scip",
  1,
  scip__protocol_version__enum_values_by_number,
  1,
  scip__protocol_version__enum_values_by_name,
  1,
  scip__protocol_version__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue scip__text_encoding__enum_values_by_number[3] =
{
  { "UnspecifiedTextEncoding", "SCIP__TEXT_ENCODING__UnspecifiedTextEncoding", 0 },
  { "UTF8", "SCIP__TEXT_ENCODING__UTF8", 1 },
  { "UTF16", "SCIP__TEXT_ENCODING__UTF16", 2 },
};
static const ProtobufCIntRange scip__text_encoding__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex scip__text_encoding__enum_values_by_name[3] =
{
  { "UTF16", 2 },
  { "UTF8", 1 },
  { "UnspecifiedTextEncoding", 0 },
};
const ProtobufCEnumDescriptor scip__text_encoding__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "scip.TextEncoding",
  "TextEncoding",
  "Scip__TextEncoding",
  "scip",
  3,
  scip__text_encoding__enum_values_by_number,
  3,
  scip__text_encoding__enum_values_by_name,
  1,
  scip__text_encoding__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue scip__position_encoding__enum_values_by_number[4] =
{
  { "UnspecifiedPositionEncoding", "SCIP__POSITION_ENCODING__UnspecifiedPositionEncoding", 0 },
  { "UTF8CodeUnitOffsetFromLineStart", "SCIP__POSITION_ENCODING__UTF8CodeUnitOffsetFromLineStart", 1 },
  { "UTF16CodeUnitOffsetFromLineStart", "SCIP__POSITION_ENCODING__UTF16CodeUnitOffsetFromLineStart", 2 },
  { "UTF32CodeUnitOffsetFromLineStart", "SCIP__POSITION_ENCODING__UTF32CodeUnitOffsetFromLineStart", 3 },
};
static const ProtobufCIntRange scip__position_encoding__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex scip__position_encoding__enum_values_by_name[4] =
{
  { "UTF16CodeUnitOffsetFromLineStart", 2 },
  { "UTF32CodeUnitOffsetFromLineStart", 3 },
  { "UTF8CodeUnitOffsetFromLineStart", 1 },
  { "UnspecifiedPositionEncoding", 0 },
};
const ProtobufCEnumDescriptor scip__position_encoding__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "scip.PositionEncoding",
  "PositionEncoding",
  "Scip__PositionEncoding",
  "scip",
  4,
  scip__position_encoding__enum_values_by_number,
  4,
  scip__position_encoding__enum_values_by_name,
  1,
  scip__position_encoding__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue scip__symbol_role__enum_values_by_number[8] =
{
  { "UnspecifiedSymbolRole", "SCIP__SYMBOL_ROLE__UnspecifiedSymbolRole", 0 },
  { "Definition", "SCIP__SYMBOL_ROLE__Definition", 1 },
  { "Import", "SCIP__SYMBOL_ROLE__Import", 2 },
  { "WriteAccess", "SCIP__SYMBOL_ROLE__WriteAccess", 4 },
  { "ReadAccess", "SCIP__SYMBOL_ROLE__ReadAccess", 8 },
  { "Generated", "SCIP__SYMBOL_ROLE__Generated", 16 },
  { "Test", "SCIP__SYMBOL_ROLE__Test", 32 },
  { "ForwardDefinition", "SCIP__SYMBOL_ROLE__ForwardDefinition", 64 },
};
static const ProtobufCIntRange scip__symbol_role__value_ranges[] = {
{0, 0},{4, 3},{8, 4},{16, 5},{32, 6},{64, 7},{0, 8}
};
static const ProtobufCEnumValueIndex scip__symbol_role__enum_values_by_name[8] =
{
  { "Definition", 1 },
  { "ForwardDefinition", 7 },
  { "Generated", 5 },
  { "Import", 2 },
  { "ReadAccess", 4 },
  { "Test", 6 },
  { "UnspecifiedSymbolRole", 0 },
  { "WriteAccess", 3 },
};
const ProtobufCEnumDescriptor scip__symbol_role__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "scip.SymbolRole",
  "SymbolRole",
  "Scip__SymbolRole",
  "scip",
  8,
  scip__symbol_role__enum_values_by_number,
  8,
  scip__symbol_role__enum_values_by_name,
  6,
  scip__symbol_role__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue scip__syntax_kind__enum_values_by_number[37] =
{
  { "UnspecifiedSyntaxKind", "SCIP__SYNTAX_KIND__UnspecifiedSyntaxKind", 0 },
  { "Comment", "SCIP__SYNTAX_KIND__Comment", 1 },
  { "PunctuationDelimiter", "SCIP__SYNTAX_KIND__PunctuationDelimiter", 2 },
  { "PunctuationBracket", "SCIP__SYNTAX_KIND__PunctuationBracket", 3 },
  { "Keyword", "SCIP__SYNTAX_KIND__Keyword", 4 },
  { "IdentifierOperator", "SCIP__SYNTAX_KIND__IdentifierOperator", 5 },
  { "Identifier", "SCIP__SYNTAX_KIND__Identifier", 6 },
  { "IdentifierBuiltin", "SCIP__SYNTAX_KIND__IdentifierBuiltin", 7 },
  { "IdentifierNull", "SCIP__SYNTAX_KIND__IdentifierNull", 8 },
  { "IdentifierConstant", "SCIP__SYNTAX_KIND__IdentifierConstant", 9 },
  { "IdentifierMutableGlobal", "SCIP__SYNTAX_KIND__IdentifierMutableGlobal", 10 },
  { "IdentifierParameter", "SCIP__SYNTAX_KIND__IdentifierParameter", 11 },
  { "IdentifierLocal", "SCIP__SYNTAX_KIND__IdentifierLocal", 12 },
  { "IdentifierShadowed", "SCIP__SYNTAX_KIND__IdentifierShadowed", 13 },
  { "IdentifierNamespace", "SCIP__SYNTAX_KIND__IdentifierNamespace", 14 },
  { "IdentifierFunction", "SCIP__SYNTAX_KIND__IdentifierFunction", 15 },
  { "IdentifierFunctionDefinition", "SCIP__SYNTAX_KIND__IdentifierFunctionDefinition", 16 },
  { "IdentifierMacro", "SCIP__SYNTAX_KIND__IdentifierMacro", 17 },
  { "IdentifierMacroDefinition", "SCIP__SYNTAX_KIND__IdentifierMacroDefinition", 18 },
  { "IdentifierType", "SCIP__SYNTAX_KIND__IdentifierType", 19 },
  { "IdentifierBuiltinType", "SCIP__SYNTAX_KIND__IdentifierBuiltinType", 20 },
  { "IdentifierAttribute", "SCIP__SYNTAX_KIND__IdentifierAttribute", 21 },
  { "RegexEscape", "SCIP__SYNTAX_KIND__RegexEscape", 22 },
  { "RegexRepeated", "SCIP__SYNTAX_KIND__RegexRepeated", 23 },
  { "RegexWildcard", "SCIP__SYNTAX_KIND__RegexWildcard", 24 },
  { "RegexDelimiter", "SCIP__SYNTAX_KIND__RegexDelimiter", 25 },
  { "RegexJoin", "SCIP__SYNTAX_KIND__RegexJoin", 26 },
  { "StringLiteral", "SCIP__SYNTAX_KIND__StringLiteral", 27 },
  { "StringLiteralEscape", "SCIP__SYNTAX_KIND__StringLiteralEscape", 28 },
  { "StringLiteralSpecial", "SCIP__SYNTAX_KIND__StringLiteralSpecial", 29 },
  { "StringLiteralKey", "SCIP__SYNTAX_KIND__StringLiteralKey", 30 },
  { "CharacterLiteral", "SCIP__SYNTAX_KIND__CharacterLiteral", 31 },
  { "NumericLiteral", "SCIP__SYNTAX_KIND__NumericLiteral", 32 },
  { "BooleanLiteral", "SCIP__SYNTAX_KIND__BooleanLiteral", 33 },
  { "Tag", "SCIP__SYNTAX_KIND__Tag", 34 },
  { "TagAttribute", "SCIP__SYNTAX_KIND__TagAttribute", 35 },
  { "TagDelimiter", "SCIP__SYNTAX_KIND__TagDelimiter", 36 },
};
static const ProtobufCIntRange scip__syntax_kind__value_ranges[] = {
{0, 0},{0, 37}
};
static const ProtobufCEnumValueIndex scip__syntax_kind__enum_values_by_name[39] =
{
  { "BooleanLiteral", 33 },
  { "CharacterLiteral", 31 },
  { "Comment", 1 },
  { "Identifier", 6 },
  { "IdentifierAttribute", 21 },
  { "IdentifierBuiltin", 7 },
  { "IdentifierBuiltinType", 20 },
  { "IdentifierConstant", 9 },
  { "IdentifierFunction", 15 },
  { "IdentifierFunctionDefinition", 16 },
  { "IdentifierKeyword", 4 },
  { "IdentifierLocal", 12 },
  { "IdentifierMacro", 17 },
  { "IdentifierMacroDefinition", 18 },
  { "IdentifierModule", 14 },
  { "IdentifierMutableGlobal", 10 },
  { "IdentifierNamespace", 14 },
  { "IdentifierNull", 8 },
  { "IdentifierOperator", 5 },
  { "IdentifierParameter", 11 },
  { "IdentifierShadowed", 13 },
  { "IdentifierType", 19 },
  { "Keyword", 4 },
  { "NumericLiteral", 32 },
  { "PunctuationBracket", 3 },
  { "PunctuationDelimiter", 2 },
  { "RegexDelimiter", 25 },
  { "RegexEscape", 22 },
  { "RegexJoin", 26 },
  { "RegexRepeated", 23 },
  { "RegexWildcard", 24 },
  { "StringLiteral", 27 },
  { "StringLiteralEscape", 28 },
  { "StringLiteralKey", 30 },
  { "StringLiteralSpecial", 29 },
  { "Tag", 34 },
  { "TagAttribute", 35 },
  { "TagDelimiter", 36 },
  { "UnspecifiedSyntaxKind", 0 },
};
const ProtobufCEnumDescriptor scip__syntax_kind__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "scip.SyntaxKind",
  "SyntaxKind",
  "Scip__SyntaxKind",
  "scip",
  37,
  scip__syntax_kind__enum_values_by_number,
  39,
  scip__syntax_kind__enum_values_by_name,
  1,
  scip__syntax_kind__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue scip__severity__enum_values_by_number[5] =
{
  { "UnspecifiedSeverity", "SCIP__SEVERITY__UnspecifiedSeverity", 0 },
  { "Error", "SCIP__SEVERITY__Error", 1 },
  { "Warning", "SCIP__SEVERITY__Warning", 2 },
  { "Information", "SCIP__SEVERITY__Information", 3 },
  { "Hint", "SCIP__SEVERITY__Hint", 4 },
};
static const ProtobufCIntRange scip__severity__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex scip__severity__enum_values_by_name[5] =
{
  { "Error", 1 },
  { "Hint", 4 },
  { "Information", 3 },
  { "UnspecifiedSeverity", 0 },
  { "Warning", 2 },
};
const ProtobufCEnumDescriptor scip__severity__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "scip.Severity",
  "Severity",
  "Scip__Severity",
  "scip",
  5,
  scip__severity__enum_values_by_number,
  5,
  scip__severity__enum_values_by_name,
  1,
  scip__severity__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue scip__diagnostic_tag__enum_values_by_number[3] =
{
  { "UnspecifiedDiagnosticTag", "SCIP__DIAGNOSTIC_TAG__UnspecifiedDiagnosticTag", 0 },
  { "Unnecessary", "SCIP__DIAGNOSTIC_TAG__Unnecessary", 1 },
  { "Deprecated", "SCIP__DIAGNOSTIC_TAG__Deprecated", 2 },
};
static const ProtobufCIntRange scip__diagnostic_tag__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex scip__diagnostic_tag__enum_values_by_name[3] =
{
  { "Deprecated", 2 },
  { "Unnecessary", 1 },
  { "UnspecifiedDiagnosticTag", 0 },
};
const ProtobufCEnumDescriptor scip__diagnostic_tag__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "scip.DiagnosticTag",
  "DiagnosticTag",
  "Scip__DiagnosticTag",
  "scip",
  3,
  scip__diagnostic_tag__enum_values_by_number,
  3,
  scip__diagnostic_tag__enum_values_by_name,
  1,
  scip__diagnostic_tag__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue scip__language__enum_values_by_number[110] =
{
  { "UnspecifiedLanguage", "SCIP__LANGUAGE__UnspecifiedLanguage", 0 },
  { "CSharp", "SCIP__LANGUAGE__CSharp", 1 },
  { "Swift", "SCIP__LANGUAGE__Swift", 2 },
  { "Dart", "SCIP__LANGUAGE__Dart", 3 },
  { "Kotlin", "SCIP__LANGUAGE__Kotlin", 4 },
  { "Scala", "SCIP__LANGUAGE__Scala", 5 },
  { "Java", "SCIP__LANGUAGE__Java", 6 },
  { "Groovy", "SCIP__LANGUAGE__Groovy", 7 },
  { "Clojure", "SCIP__LANGUAGE__Clojure", 8 },
  { "CommonLisp", "SCIP__LANGUAGE__CommonLisp", 9 },
  { "Scheme", "SCIP__LANGUAGE__Scheme", 10 },
  { "Racket", "SCIP__LANGUAGE__Racket", 11 },
  { "Lua", "SCIP__LANGUAGE__Lua", 12 },
  { "Perl", "SCIP__LANGUAGE__Perl", 13 },
  { "Raku", "SCIP__LANGUAGE__Raku", 14 },
  { "Python", "SCIP__LANGUAGE__Python", 15 },
  { "Ruby", "SCIP__LANGUAGE__Ruby", 16 },
  { "Elixir", "SCIP__LANGUAGE__Elixir", 17 },
  { "Erlang", "SCIP__LANGUAGE__Erlang", 18 },
  { "PHP", "SCIP__LANGUAGE__PHP", 19 },
  { "Hack", "SCIP__LANGUAGE__Hack", 20 },
  { "Coffeescript", "SCIP__LANGUAGE__Coffeescript", 21 },
  { "JavaScript", "SCIP__LANGUAGE__JavaScript", 22 },
  { "TypeScript", "SCIP__LANGUAGE__TypeScript", 23 },
  { "Flow", "SCIP__LANGUAGE__Flow", 24 },
  { "Vue", "SCIP__LANGUAGE__Vue", 25 },
  { "CSS", "SCIP__LANGUAGE__CSS", 26 },
  { "Less", "SCIP__LANGUAGE__Less", 27 },
  { "Sass", "SCIP__LANGUAGE__Sass", 28 },
  { "SCSS", "SCIP__LANGUAGE__SCSS", 29 },
  { "HTML", "SCIP__LANGUAGE__HTML", 30 },
  { "XML", "SCIP__LANGUAGE__XML", 31 },
  { "XSL", "SCIP__LANGUAGE__XSL", 32 },
  { "Go", "SCIP__LANGUAGE__Go", 33 },
  { "C", "SCIP__LANGUAGE__C", 34 },
  { "CPP", "SCIP__LANGUAGE__CPP", 35 },
  { "Objective_C", "SCIP__LANGUAGE__Objective_C", 36 },
  { "Objective_CPP", "SCIP__LANGUAGE__Objective_CPP", 37 },
  { "Zig", "SCIP__LANGUAGE__Zig", 38 },
  { "Ada", "SCIP__LANGUAGE__Ada", 39 },
  { "Rust", "SCIP__LANGUAGE__Rust", 40 },
  { "OCaml", "SCIP__LANGUAGE__OCaml", 41 },
  { "FSharp", "SCIP__LANGUAGE__FSharp", 42 },
  { "SML", "SCIP__LANGUAGE__SML", 43 },
  { "Haskell", "SCIP__LANGUAGE__Haskell", 44 },
  { "Agda", "SCIP__LANGUAGE__Agda", 45 },
  { "Idris", "SCIP__LANGUAGE__Idris", 46 },
  { "Coq", "SCIP__LANGUAGE__Coq", 47 },
  { "Lean", "SCIP__LANGUAGE__Lean", 48 },
  { "APL", "SCIP__LANGUAGE__APL", 49 },
  { "Dyalog", "SCIP__LANGUAGE__Dyalog", 50 },
  { "J", "SCIP__LANGUAGE__J", 51 },
  { "Matlab", "SCIP__LANGUAGE__Matlab", 52 },
  { "Wolfram", "SCIP__LANGUAGE__Wolfram", 53 },
  { "R", "SCIP__LANGUAGE__R", 54 },
  { "Julia", "SCIP__LANGUAGE__Julia", 55 },
  { "Fortran", "SCIP__LANGUAGE__Fortran", 56 },
  { "Delphi", "SCIP__LANGUAGE__Delphi", 57 },
  { "Assembly", "SCIP__LANGUAGE__Assembly", 58 },
  { "COBOL", "SCIP__LANGUAGE__COBOL", 59 },
  { "ABAP", "SCIP__LANGUAGE__ABAP", 60 },
  { "SAS", "SCIP__LANGUAGE__SAS", 61 },
  { "Razor", "SCIP__LANGUAGE__Razor", 62 },
  { "VisualBasic", "SCIP__LANGUAGE__VisualBasic", 63 },
  { "ShellScript", "SCIP__LANGUAGE__ShellScript", 64 },
  { "Fish", "SCIP__LANGUAGE__Fish", 65 },
  { "Awk", "SCIP__LANGUAGE__Awk", 66 },
  { "PowerShell", "SCIP__LANGUAGE__PowerShell", 67 },
  { "Bat", "SCIP__LANGUAGE__Bat", 68 },
  { "SQL", "SCIP__LANGUAGE__SQL", 69 },
  { "PLSQL", "SCIP__LANGUAGE__PLSQL", 70 },
  { "Prolog", "SCIP__LANGUAGE__Prolog", 71 },
  { "Ini", "SCIP__LANGUAGE__Ini", 72 },
  { "TOML", "SCIP__LANGUAGE__TOML", 73 },
  { "YAML", "SCIP__LANGUAGE__YAML", 74 },
  { "JSON", "SCIP__LANGUAGE__JSON", 75 },
  { "Jsonnet", "SCIP__LANGUAGE__Jsonnet", 76 },
  { "Nix", "SCIP__LANGUAGE__Nix", 77 },
  { "Skylark", "SCIP__LANGUAGE__Skylark", 78 },
  { "Makefile", "SCIP__LANGUAGE__Makefile", 79 },
  { "Dockerfile", "SCIP__LANGUAGE__Dockerfile", 80 },
  { "BibTeX", "SCIP__LANGUAGE__BibTeX", 81 },
  { "TeX", "SCIP__LANGUAGE__TeX", 82 },
  { "LaTeX", "SCIP__LANGUAGE__LaTeX", 83 },
  { "Markdown", "SCIP__LANGUAGE__Markdown", 84 },
  { "ReST", "SCIP__LANGUAGE__ReST", 85 },
  { "AsciiDoc", "SCIP__LANGUAGE__AsciiDoc", 86 },
  { "Diff", "SCIP__LANGUAGE__Diff", 88 },
  { "Git_Config", "SCIP__LANGUAGE__Git_Config", 89 },
  { "Handlebars", "SCIP__LANGUAGE__Handlebars", 90 },
  { "Git_Commit", "SCIP__LANGUAGE__Git_Commit", 91 },
  { "Git_Rebase", "SCIP__LANGUAGE__Git_Rebase", 92 },
  { "JavaScriptReact", "SCIP__LANGUAGE__JavaScriptReact", 93 },
  { "TypeScriptReact", "SCIP__LANGUAGE__TypeScriptReact", 94 },
  { "Solidity", "SCIP__LANGUAGE__Solidity", 95 },
  { "Apex", "SCIP__LANGUAGE__Apex", 96 },
  { "CUDA", "SCIP__LANGUAGE__CUDA", 97 },
  { "GraphQL", "SCIP__LANGUAGE__GraphQL", 98 },
  { "Pascal", "SCIP__LANGUAGE__Pascal", 99 },
  { "Protobuf", "SCIP__LANGUAGE__Protobuf", 100 },
  { "Tcl", "SCIP__LANGUAGE__Tcl", 101 },
  { "Repro", "SCIP__LANGUAGE__Repro", 102 },
  { "Thrift", "SCIP__LANGUAGE__Thrift", 103 },
  { "Verilog", "SCIP__LANGUAGE__Verilog", 104 },
  { "VHDL", "SCIP__LANGUAGE__VHDL", 105 },
  { "Svelte", "SCIP__LANGUAGE__Svelte", 106 },
  { "Slang", "SCIP__LANGUAGE__Slang", 107 },
  { "Luau", "SCIP__LANGUAGE__Luau", 108 },
  { "Justfile", "SCIP__LANGUAGE__Justfile", 109 },
  { "Nickel", "SCIP__LANGUAGE__Nickel", 110 },
};
static const ProtobufCIntRange scip__language__value_ranges[] = {
{0, 0},{88, 87},{0, 110}
};
static const ProtobufCEnumValueIndex scip__language__enum_values_by_name[110] =
{
  { "ABAP", 60 },
  { "APL", 49 },
  { "Ada", 39 },
  { "Agda", 45 },
  { "Apex", 95 },
  { "AsciiDoc", 86 },
  { "Assembly", 58 },
  { "Awk", 66 },
  { "Bat", 68 },
  { "BibTeX", 81 },
  { "C", 34 },
  { "COBOL", 59 },
  { "CPP", 35 },
  { "CSS", 26 },
  { "CSharp", 1 },
  { "CUDA", 96 },
  { "Clojure", 8 },
  { "Coffeescript", 21 },
  { "CommonLisp", 9 },
  { "Coq", 47 },
  { "Dart", 3 },
  { "Delphi", 57 },
  { "Diff", 87 },
  { "Dockerfile", 80 },
  { "Dyalog", 50 },
  { "Elixir", 17 },
  { "Erlang", 18 },
  { "FSharp", 42 },
  { "Fish", 65 },
  { "Flow", 24 },
  { "Fortran", 56 },
  { "Git_Commit", 90 },
  { "Git_Config", 88 },
  { "Git_Rebase", 91 },
  { "Go", 33 },
  { "GraphQL", 97 },
  { "Groovy", 7 },
  { "HTML", 30 },
  { "Hack", 20 },
  { "Handlebars", 89 },
  { "Haskell", 44 },
  { "Idris", 46 },
  { "Ini", 72 },
  { "J", 51 },
  { "JSON", 75 },
  { "Java", 6 },
  { "JavaScript", 22 },
  { "JavaScriptReact", 92 },
  { "Jsonnet", 76 },
  { "Julia", 55 },
  { "Justfile", 108 },
  { "Kotlin", 4 },
  { "LaTeX", 83 },
  { "Lean", 48 },
  { "Less", 27 },
  { "Lua", 12 },
  { "Luau", 107 },
  { "Makefile", 79 },
  { "Markdown", 84 },
  { "Matlab", 52 },
  { "Nickel", 109 },
  { "Nix", 77 },
  { "OCaml", 41 },
  { "Objective_C", 36 },
  { "Objective_CPP", 37 },
  { "PHP", 19 },
  { "PLSQL", 70 },
  { "Pascal", 98 },
  { "Perl", 13 },
  { "PowerShell", 67 },
  { "Prolog", 71 },
  { "Protobuf", 99 },
  { "Python", 15 },
  { "R", 54 },
  { "Racket", 11 },
  { "Raku", 14 },
  { "Razor", 62 },
  { "ReST", 85 },
  { "Repro", 101 },
  { "Ruby", 16 },
  { "Rust", 40 },
  { "SAS", 61 },
  { "SCSS", 29 },
  { "SML", 43 },
  { "SQL", 69 },
  { "Sass", 28 },
  { "Scala", 5 },
  { "Scheme", 10 },
  { "ShellScript", 64 },
  { "Skylark", 78 },
  { "Slang", 106 },
  { "Solidity", 94 },
  { "Svelte", 105 },
  { "Swift", 2 },
  { "TOML", 73 },
  { "Tcl", 100 },
  { "TeX", 82 },
  { "Thrift", 102 },
  { "TypeScript", 23 },
  { "TypeScriptReact", 93 },
  { "UnspecifiedLanguage", 0 },
  { "VHDL", 104 },
  { "Verilog", 103 },
  { "VisualBasic", 63 },
  { "Vue", 25 },
  { "Wolfram", 53 },
  { "XML", 31 },
  { "XSL", 32 },
  { "YAML", 74 },
  { "Zig", 38 },
};
const ProtobufCEnumDescriptor scip__language__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "scip.Language",
  "Language",
  "Scip__Language",
  "scip",
  110,
  scip__language__enum_values_by_number,
  110,
  scip__language__enum_values_by_name,
  2,
  scip__language__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
